# change source and team
source: https://<GIT_SERVER>/<TEAM_NAME>/mlops-gitops.git
team: <TEAM_NAME>
release: mlops

applications:
  # Tooling to support CI/CD
  - name: toolings
    enabled: true
    source_path: "."
    helm_values:
      - toolings/values.yaml
